
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
#    fetch-registry: true

spring:
#  spring:
#    profiles:
#      active: dev
  application:
    name: bootcamp-shopvintage-auctions
  config:
    import: optional:configserver:http://localhost:8888
